export const RUTAS = {
  raiz: '/',
  ingresar: '/ingresar',
  registro: '/registro',
  recuperar: '/recuperar',
  nuevaClave: '/nueva-clave',
  proyectos: '/proyectos',
  perfil: '/perfil',
  catalogo: '/catalogo',
  catalogoActividades: '/catalogo/actividades',
  catalogoInsumos: '/catalogo/insumos',
  actividad: (id = ':actividadId') => `/catalogo/actividades/${id}`,
  proyecto: (id = ':proyectoId') => `/proyectos/${id}`,
  presupuesto: (id = ':proyectoId') => `/proyectos/${id}/presupuesto`,
  memorias: (id = ':proyectoId') => `/proyectos/${id}/memorias`,
  programacion: (id = ':proyectoId') => `/proyectos/${id}/programacion`,
  insumos: (id = ':proyectoId') => `/proyectos/${id}/insumos`,
  apu: (id = ':proyectoId') => `/proyectos/${id}/apu`,
  especificaciones: (id = ':proyectoId') => `/proyectos/${id}/especificaciones`,
  actas: (id = ':proyectoId') => `/proyectos/${id}/actas`,
  bitacora: (id = ':proyectoId') => `/proyectos/${id}/bitacora`,
  ajustes: (id = ':proyectoId') => `/proyectos/${id}/ajustes`,
} as const;
